message: 'Say Hallo'

spring:
  profiles: default
  
eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/
  instance:
    status-page-url-path: /rest/info
    health-check-url-path: /rest/health
