message: 'Say Hallo'

spring:
  profiles: default
  
eureka:
  client:
    serviceUrl:
        defaultZone: https://xd-discovery-server.herokuapp.com/
  instance:
    status-page-url-path: /rest/info
    health-check-url-path: /rest/health
