message: 'Say Hallo'

spring:
  profiles: default
  
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /rest/info
    health-check-url-path: /rest/health
