message: 'Say Hallo'

 eureka:
    client:
      serviceUrl:
       defaultZone: https://xd-discovery-server.herokuapp.com/eureka/
   instance:
     status-page-url-path: /rest/info
     health-check-url-path: /rest/health
